[project]
authors = ["Jermiah Joseph <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge"]
name = "snakemake-interface-common"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11"


# [project.optional-dependencies]
# dev = [
#   "black>=22.1.0",
#   "coverage[toml]>=6.3.1",
#   "flake8>=4.0.1",
#   "flake8-bugbear>=22.1.11",
#   "pytest>=7.0",
# ]


[pypi-dependencies]
snakemake-interface-common = { path = ".", editable = true }

[feature.dev.dependencies]
pytest = ">=8.3.5,<9"
ruff = ">=0.10.0,<0.11"

[environments]
dev = ["dev"]
