name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore: []

permissions:
  contents: read
  checks: write
  issues: write
  pull-requests: write

jobs:
  quality-control:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          environments: dev

      - name: Ruff Format
        if: always()
        run: |
          pixi run --environment dev format --check

      - name: Ruff lint
        if: always()
        run: |
          pixi run --environment dev lint --diff

      - name: Mypy
        if: always()
        run: |
          pixi run --environment dev type-check

      - name: Collect QC
        run: echo "All quality control checks passed"

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          environments: dev

      - name: Run tests
        run: pixi run --environment dev test --show-capture=all -s -vv

  test-min-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.3
        with:
          environments: minpyver

      - name: Run tests with min python
        run: pixi run --environment minpyver test-min-python -v